<?php

require "config/user.php";
$user = null;

if (isset($_POST["username"]) && isset($_POST["password"])) {
    $user = new User();
    $authentificate = $user->login($_POST["username"], $_POST["password"]);
    if ($authentificate != null) {
        $user->createSession($authentificate);
        if (isset($_POST["rememberMe"])) {
            $user->rememberUser($authentificate);
        }
        header("location: index.php?route=profile");
        exit();
    }
}

?>
<main>
    <h1>Connexion</h1>
    <?php if ($user && $user->getErrorLogin()) { ?>
        <p> <?= $user->getErrorLogin() ?> </p>
    <?php } ?>
    <?php if ($user && $user->getSuccessLogin()) { ?>
        <p> <?= $user->getSuccessLogin() ?> </p>
    <?php } ?>
    <form method="post">
        <div>
            <label for="username">Nom :</label>
            <input type="text" id="username" name="username">
        </div>
        <div>
            <label for="password">Mot de Passe :</label>
            <input type="password" id="password" name="password">
        </div>
        <div>
            <label for="check">Se souvenir de moi</label>
            <input type="checkbox" name="rememberMe" id="rememberMe">
        </div>
        <button type="submit">
            Se connecter
        </button>
    </form>
</main>